name: Foundry lcov report
description: Compares lcov on default branch against the pr

runs:
  using: "composite"
  steps:
    - name: Download previous sizes report
      if: ${{ github.event_name == 'pull_request' }}
      uses: dawidd6/action-download-artifact@d63b86af1b34672e53c440b1b83979861906bad7 # v24
      with:
        branch: ${{ github.base_ref }}
        name: lcov-report
        if_no_artifact_found: warn
        path: lcov
        check_artifacts: true

    - uses: aave-dao/action-foundry-lcov@main
      id: lcov
      with:
        # The path to the first contract to compare
        ROOT_REPORT_PATH: "lcov/lcov.info"
        # The path to the second contract to compare
        REPORT_PATH: "lcov.info"

    - name: Prepare comment
      shell: bash
      run: |
        printf '%s' "${{ steps.lcov.outputs.report }}" > /tmp/content/lcov.txt

    - name: Move lcov to cache
      shell: bash
      run: |
        mkdir -p lcov
        mv lcov.info lcov/lcov.info

    - name: Cache Save
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      with:
        name: lcov-report
        path: lcov/lcov.info
