name: Foundry setup
description: A generalized foundry setup doing common things, like building and emitting a version.

runs:
  using: "composite"
  steps:
    - name: Make empty dir content tmp dir
      shell: bash
      run: mkdir -p /tmp/content

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@908c540300062bd5a7e473851cdb4282204cee09 # v1.9.1
      with:
        version: v1.8.3

    - name: Run Forge version
      shell: bash
      run: |
        forge --version
        forge cache ls
      id: version
