name: Foundry setup
description: A generalized foundry setup doing common things, like building and emitting a version.
inputs:
  FOUNDRY_VERSION:
    description: "The Foundry version to install: stable, nightly, or a SemVer version such as v1.8.0 or v1.7.0"
    default: "stable"

runs:
  using: "composite"
  steps:
    - name: Make empty dir content tmp dir
      shell: bash
      run: mkdir -p /tmp/content

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@908c540300062bd5a7e473851cdb4282204cee09 # v1.9.1
      with:
        version: ${{ inputs.FOUNDRY_VERSION }}

    - name: Run Forge version
      shell: bash
      run: |
        forge --version
        forge cache ls
      id: version
