name: Foundry gas report
description: Compares gas on default branch against the pr

runs:
  using: "composite"
  steps:
    - uses: aave-dao/action-foundry-gas-diff@main
      id: gas

    - name: Prepare comment
      shell: bash
      env:
        REPORT: ${{ steps.gas.outputs.report }}
      run: |
        printf '%s' "$REPORT" > /tmp/content/gas.txt