name: Foundry gas report
description: Compares gas on default branch against the pr

runs:
  using: "composite"
  steps:
    - uses: aave-dao/action-foundry-gas-diff@main
      id: gas

    - name: Prepare comment
      if: ${{ !contains(steps.gas.outputs.report, 'Seems like you are not measuring gas of any operations yet.') }}
      shell: bash
      run: |
        printf '%s' "${{ steps.gas.outputs.report }}" > /tmp/content/gas.txt
